import type { ArchiveEntry, RawRecipeEntry } from "./types";

const recipePathPattern = /^data\/([^/]+)\/(?:recipe|recipes)\/(.+)\.json$/;

export function extractRecipes(entries: ArchiveEntry[]): RawRecipeEntry[] {
  const recipes: RawRecipeEntry[] = [];

  for (const entry of entries) {
    const match = entry.path.match(recipePathPattern);
    if (!match) {
      continue;
    }

    try {
      const namespace = match[1];
      const recipePath = match[2];
      recipes.push({
        id: `${namespace}:${recipePath}`,
        namespace,
        path: recipePath,
        raw: JSON.parse(entry.content.toString("utf8"))
      });
    } catch {
      // Invalid recipe JSON is ignored at extraction time; archive-level warnings
      // are generated by the caller when counts look suspicious.
    }
  }

  return recipes;
}
