import type { ItemDefinition } from "../../calculator-core/types";

export const items: ItemDefinition[] = [
  {
    id: "minecraft:cobblestone",
    name: "Cobblestone",
    stackSize: 64,
    sourceType: "generated",
    notes: "Generated by a cobblestone generator with Mechanical Drills."
  },
  { id: "minecraft:gravel", name: "Gravel", stackSize: 64, sourceType: "raw" },
  { id: "minecraft:sand", name: "Sand", stackSize: 64, sourceType: "raw" },
  { id: "minecraft:flint", name: "Flint", stackSize: 64, sourceType: "byproduct" },
  { id: "minecraft:clay_ball", name: "Clay Ball", stackSize: 64, sourceType: "raw" },
  { id: "minecraft:soul_sand", name: "Soul Sand", stackSize: 64, sourceType: "raw" },
  { id: "minecraft:oak_log", name: "Oak Log", stackSize: 64, sourceType: "raw" },
  { id: "minecraft:oak_planks", name: "Oak Planks", stackSize: 64, sourceType: "raw" },
  { id: "minecraft:wheat", name: "Wheat", stackSize: 64, sourceType: "raw" },
  { id: "create:wheat_flour", name: "Wheat Flour", stackSize: 64, sourceType: "raw" },
  { id: "minecraft:iron_ingot", name: "Iron Ingot", stackSize: 64, sourceType: "raw" },
  { id: "create:iron_sheet", name: "Iron Sheet", stackSize: 64, sourceType: "raw" },
  { id: "minecraft:andesite", name: "Andesite", stackSize: 64, sourceType: "raw" },
  { id: "minecraft:iron_nugget", name: "Iron Nugget", stackSize: 64, sourceType: "raw" },
  {
    id: "create:andesite_alloy",
    name: "Andesite Alloy",
    stackSize: 64,
    sourceType: "raw"
  },
  { id: "minecraft:copper_ingot", name: "Copper Ingot", stackSize: 64, sourceType: "raw" },
  { id: "create:zinc_ingot", name: "Zinc Ingot", stackSize: 64, sourceType: "raw" },
  { id: "create:brass_ingot", name: "Brass Ingot", stackSize: 64, sourceType: "raw" },
  { id: "minecraft:gold_ingot", name: "Gold Ingot", stackSize: 64, sourceType: "raw" },
  { id: "create:golden_sheet", name: "Golden Sheet", stackSize: 64, sourceType: "raw" },
  { id: "create:cogwheel", name: "Cogwheel", stackSize: 64, sourceType: "raw" },
  {
    id: "create:precision_mechanism",
    name: "Precision Mechanism",
    stackSize: 64,
    sourceType: "raw",
    notes: "Sequenced assembly placeholder for the MVP."
  }
];

export const itemById = items.reduce<Record<string, ItemDefinition>>((acc, item) => {
  acc[item.id] = item;
  return acc;
}, {});
